jwt:
  secret: YWFzbGtqZGx6a3huY21haHJvd3VlaHJzbWRueGtqZGhmbGtzZGhmd2VsdXJoc2tmbnNk

server:
  port: 8080

client:
  host:
    url: http://localhost:3000

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://dev/mybob
    username: dev
    password: dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100
  data:
    redis:
      host: localhost
      port: 6379